version: 2

models:

  # ===========================
  # Demand Forecast
  # ===========================

  - name: staging_v1_meteologica_pjm_demand_forecast_hourly
    description: '{{ doc("meteologica_pjm_demand_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
        tests:
          - not_null
      - name: forecast_execution_datetime
        description: '{{ doc("col_forecast_execution_datetime") }}'
        tests:
          - not_null
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
        tests:
          - not_null
      - name: forecast_datetime
        description: '{{ doc("col_forecast_datetime") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
        tests:
          - not_null
      - name: date_utc
        description: '{{ doc("col_date_utc") }}'
        tests:
          - not_null
      - name: hour_ending_utc
        description: '{{ doc("col_hour_ending_utc") }}'
        tests:
          - not_null
      - name: region
        description: '{{ doc("col_meteologica_region") }}'
        tests:
          - not_null
          - accepted_values:
              values:
                - 'RTO'
                - 'MIDATL'
                - 'SOUTH'
                - 'WEST'
                - 'MIDATL_AE'
                - 'MIDATL_BC'
                - 'MIDATL_DPL'
                - 'MIDATL_DPL_DPLCO'
                - 'MIDATL_DPL_EASTON'
                - 'MIDATL_JC'
                - 'MIDATL_ME'
                - 'MIDATL_PE'
                - 'MIDATL_PEP'
                - 'MIDATL_PEP_PEPCO'
                - 'MIDATL_PEP_SMECO'
                - 'MIDATL_PL'
                - 'MIDATL_PL_PLCO'
                - 'MIDATL_PL_UGI'
                - 'MIDATL_PN'
                - 'MIDATL_PS'
                - 'MIDATL_RECO'
                - 'SOUTH_DOM'
                - 'WEST_AEP'
                - 'WEST_AEP_AEPAPT'
                - 'WEST_AEP_AEPIMP'
                - 'WEST_AEP_AEPKPT'
                - 'WEST_AEP_AEPOPT'
                - 'WEST_AP'
                - 'WEST_ATSI'
                - 'WEST_ATSI_OE'
                - 'WEST_ATSI_PAPWR'
                - 'WEST_CE'
                - 'WEST_DAY'
                - 'WEST_DEOK'
                - 'WEST_DUQ'
                - 'WEST_EKPC'
      - name: forecast_load_mw
        description: '{{ doc("col_forecast_load_mw") }}'

  # ===========================
  # Generation Forecast
  # ===========================

  - name: staging_v1_meteologica_pjm_gen_forecast_hourly
    description: '{{ doc("meteologica_pjm_generation_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
        tests:
          - not_null
      - name: forecast_execution_datetime
        description: '{{ doc("col_forecast_execution_datetime") }}'
        tests:
          - not_null
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
        tests:
          - not_null
      - name: forecast_datetime
        description: '{{ doc("col_forecast_datetime") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
        tests:
          - not_null
      - name: date_utc
        description: '{{ doc("col_date_utc") }}'
        tests:
          - not_null
      - name: hour_ending_utc
        description: '{{ doc("col_hour_ending_utc") }}'
        tests:
          - not_null
      - name: source
        description: '{{ doc("col_generation_source") }}'
        tests:
          - not_null
          - accepted_values:
              values: ['solar', 'wind', 'hydro']
      - name: region
        description: '{{ doc("col_meteologica_region") }}'
        tests:
          - not_null
          - accepted_values:
              values:
                - 'RTO'
                - 'MIDATL'
                - 'SOUTH'
                - 'WEST'
                - 'MIDATL_AE'
                - 'MIDATL_PL'
                - 'MIDATL_PN'
                - 'SOUTH_DOM'
                - 'WEST_AEP'
                - 'WEST_AP'
                - 'WEST_ATSI'
                - 'WEST_CE'
      - name: forecast_generation_mw
        description: '{{ doc("col_forecast_generation_mw") }}'

  # ===========================
  # DA Price Forecast
  # ===========================

  - name: staging_v1_meteologica_pjm_da_price_forecast_hourly
    description: '{{ doc("meteologica_pjm_da_price_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
        tests:
          - not_null
      - name: forecast_execution_datetime
        description: '{{ doc("col_forecast_execution_datetime") }}'
        tests:
          - not_null
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
        tests:
          - not_null
      - name: forecast_datetime
        description: '{{ doc("col_forecast_datetime") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
        tests:
          - not_null
      - name: date_utc
        description: '{{ doc("col_date_utc") }}'
        tests:
          - not_null
      - name: hour_ending_utc
        description: '{{ doc("col_hour_ending_utc") }}'
        tests:
          - not_null
      - name: hub
        description: '{{ doc("col_meteologica_hub") }}'
        tests:
          - not_null
          - accepted_values:
              values:
                - 'SYSTEM'
                - 'AEP DAYTON'
                - 'AEP GEN'
                - 'ATSI GEN'
                - 'CHICAGO GEN'
                - 'CHICAGO'
                - 'DOMINION'
                - 'EASTERN'
                - 'NEW JERSEY'
                - 'N ILLINOIS'
                - 'OHIO'
                - 'WESTERN'
                - 'WEST INT'
      - name: forecast_da_price
        description: '{{ doc("col_forecast_da_price") }}'
