version: 2

sources:

  - name: clear_street_v2
    schema: clear_street
    tables:
      - name: helios_transactions_v2_2026_feb_23
      - name: helios_intraday_transactions_v2_2026_feb_23

  - name: marex_v2
    schema: marex
    tables:
      - name: helios_allocated_trades_v2_2026_feb_23