# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_azure_postgresql'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_azure_postgresql'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# ── triggers ────────────────────────────────────────────────────────────────────
# Run triggers after every dbt run
on-run-end:
  - "{{ setup_postgres_triggers() }}"

# ── seeds ────────────────────────────────────────────────────────────────────
seeds:
  dbt_azure_postgresql:
    dbt_wsi_temps_v1_2026_feb_25:
      +schema: dbt_wsi_temps_v1_2026_feb_25

# ── Models ────────────────────────────────────────────────────────────────────
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_azure_postgresql:
  
    # ── dbt ────────────────────────────────────────────────────────────────────
    dbt:
      +schema: dbt
      +materialized: view

    # ── Positions and Trades ────────────────────────────────────────────────────
    positions_and_trades:
      trades_cleaned:
        +schema: trades_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      positions_cleaned:
        +schema: positions_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Meteologica ──────────────────────────────────────────────────────────────
    meteologica:
      meteologica_cleaned:
        +schema: meteologica_cleaned
        +materialized: view
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Power ──────────────────────────────────────────────────────────────────
    power:
      pjm_cleaned:
        +schema: pjm_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        queries:
          +materialized: ephemeral
        utils:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Genscape ──────────────────────────────────────────────────────────────────
    genscape:
      genscape_cleaned:
        +schema: genscape_cleaned
        +materialized: view

