version: 2

sources:
  
  - name: wsi_v1
    schema: wsi
    tables:
      - name: daily_observed_temp_v3_2025_09_08
      - name: hourly_observed_temp_v2_20250722
      - name: hourly_forecast_temp_v4_2025_jan_12
      - name: weighted_temp_daily_forecast_city_v2_2026_jan_12
      - name: weighted_temp_daily_forecast_iso_models_v2_2026_jan_12
      - name: weighted_temp_daily_forecast_iso_wsi_v2_2026_jan_12
      - name: wsi_homepage_forecast_table_avg_v1_2026_jan_12
      - name: wsi_homepage_forecast_table_hddcdd_v1_2026_jan_12
      - name: wsi_homepage_forecast_table_minmax_v1_2026_jan_12